title: <p align="center"> Chaitanya Kumar Singh </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chaitanya-singh">LinkedIn</a> |
  <a href="https://github.com/chaitanyaksingh">GitHub</a>
  
  <br>   
  <br>
  </p>



theme: jekyll-theme-minimal
